### ISSUE TITLE
Cannot Start On Initial Install (Missing JSON File?)

### ISSUE THREAD

**Issue by andrewcooke-isti** [localstack/docs#311]
Hi,  I am trying to test localstack and did not get very far.

On Rocky 9 I created a local python3.9 venv and then installed localstack (pip install localstack).

On trying to start localstack (localstack start) I got an error indicating no docker, so I installed that (sudo yum install docker).

After that, on trying to start I see:

```
(localstack) [andrew@localhost ~]$ localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 1.2.0

[10:20:44] starting LocalStack in Docker mode 🐳               localstack.py:139
──────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────
Traceback (most recent call last):
  File "/home/andrew/localstack/bin/localstack", line 23, in <module>
    main()
  File "/home/andrew/localstack/bin/localstack", line 19, in main
    main.main()
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrew/localstack/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/cli/localstack.py", line 160, in cmd_start
    bootstrap.start_infra_in_docker()
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/bootstrap.py", line 622, in start_infra_in_docker
    prepare_docker_start()
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/bootstrap.py", line 520, in prepare_docker_start
    if DOCKER_CLIENT.is_container_running(container_name):
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/container_utils/container_client.py", line 470, in is_container_running
    return container_name in self.get_running_container_names()
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/container_utils/container_client.py", line 464, in get_running_container_names
    result = self.list_containers(all=False)
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 221, in list_containers
    container_list = [json.loads(line) for line in cmd_result.splitlines()]
  File "/home/andrew/localstack/lib64/python3.9/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 221, in <listcomp>
    container_list = [json.loads(line) for line in cmd_result.splitlines()]
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The docs said to create an issue here... (I searched issues and didn't find anything immediately obvious)

**Comment by HarshCasper** [comment]
Hi @andrewcooke-isti — Can you please try running LocalStack via Docker:

```sh
docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
```

I don't think that its an issue with LocalStack — Just the development environment issue possibly.

**Comment by andrewcooke-isti** [comment]
with teh docker running as above the web interface (dashboard) says "No LocalStack instance running - please start LocalStack or upgrade to version 1.1"

**Comment by HarshCasper** [comment]
Hi @andrewcooke-isti — In this case, you might need to start your LocalStack container with an API key. When starting LocalStack using a docker run command, you have to specify the API key using the -e flag for environment variables like this:

```sh
docker run \
  --rm -it \
  -p 4566:4566 \
  -p 4510-4559:4510-4559 \
  -e LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:- } \
  localstack/localstack
```

The `docker run` command is equivalent to LocalStack CLI 👍

**Comment by andrewcooke-isti** [comment]
how do i generate an api key?  if i just enter some arbitrary string (eg "test") nothing seems to change and nothing is defined in my environment (even after activating the venv for the install).

**Comment by andrewcooke-isti** [comment]
ah, i found an option in the web interface.  trying to start a new plan now...

**Comment by andrewcooke-isti** [comment]
ok, this seems to work, thanks.  will close, but you guys really need to work on the "getting started" part of the docs.
